# this file contains some configuration for the pyerk package

main_module = "control_theory1.py"
version = "0.2.1.0"

[pyerkdjango]

# this module will be loaded in the editor
main_module = "control_theory1.py"
