# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: 
    - main
    - develop
    - feature/test_bootstrap_ci
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

# The following command allows to connect to the ci-container via ssh
# very useful for debugging
# source: https://github.com/marketplace/actions/debugging-with-tmate

#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install addict pytest PyPDF2 pathlib black sphinx sphinx_rtd_theme
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Installing package
      run: |
        # install this package
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest
